#!/usr/bin/env python3
"""Regenerate xupin's static pinyin dictionary from rime-ice.

Downloads two files from rime-ice (GPL-3.0, https://github.com/iDvel/rime-ice) at a pinned
commit, merges them, keeps the single-character table in full and the top-N word entries by
rime-ice's own static weight, and writes:

  - entry/src/main/resources/rawfile/dict/words.dict.tsv  (runtime dictionary asset)
  - entry/src/main/ets/pinyin/syllables.ets                (legal pinyin syllable table, source)

See ../THIRD_PARTY_NOTICES.md for why these two files and this trim size were chosen.
Run from the xupin/ directory: `python3 tools/build-dict.py`
"""
import os
import sys
import urllib.request
from collections import defaultdict

RIME_ICE_COMMIT = "b681a34f788795034b3b288830f4861980bc8b0d"
RAW_BASE = f"https://raw.githubusercontent.com/iDvel/rime-ice/{RIME_ICE_COMMIT}/cn_dicts"
SOURCES = ["8105.dict.yaml", "base.dict.yaml"]
WORD_CAP = 200_000  # top-N base.dict.yaml word entries by weight; see THIRD_PARTY_NOTICES.md

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
XUPIN_ROOT = os.path.dirname(SCRIPT_DIR)
TSV_OUT = os.path.join(XUPIN_ROOT, "entry/src/main/resources/rawfile/dict/words.dict.tsv")
SYLLABLES_OUT = os.path.join(XUPIN_ROOT, "entry/src/main/ets/pinyin/syllables.ets")


def fetch_lines(filename):
    url = f"{RAW_BASE}/{filename}"
    print(f"fetching {url}", file=sys.stderr)
    with urllib.request.urlopen(url, timeout=60) as resp:
        text = resp.read().decode("utf-8")
    return text.split("\n")


def parse_rows(lines):
    rows = []
    in_body = False
    for line in lines:
        line = line.rstrip("\n")
        if not in_body:
            if line.strip() == "...":
                in_body = True
            continue
        if not line.strip() or line.startswith("#"):
            continue
        parts = line.split("\t")
        if len(parts) != 3:
            continue
        word, pinyin, weight_s = parts
        try:
            weight = int(weight_s)
        except ValueError:
            continue
        syl_list = [s for s in pinyin.strip().split(" ") if s]
        key = "".join(syl_list)
        rows.append((word, key, weight, syl_list))
    return rows


def main():
    chars = parse_rows(fetch_lines("8105.dict.yaml"))
    words = parse_rows(fetch_lines("base.dict.yaml"))
    words.sort(key=lambda r: -r[2])
    words_kept = words[:WORD_CAP]
    print(f"chars: {len(chars)}, words total: {len(words)}, kept: {len(words_kept)}", file=sys.stderr)

    syllables = set()
    entries = defaultdict(dict)
    for word, key, weight, syl_list in chars + words_kept:
        syllables.update(syl_list)
        if word not in entries[key] or entries[key][word] < weight:
            entries[key][word] = weight

    os.makedirs(os.path.dirname(TSV_OUT), exist_ok=True)
    total = 0
    with open(TSV_OUT, "w", encoding="utf-8") as out:
        for key in sorted(entries.keys()):
            for word, weight in sorted(entries[key].items(), key=lambda kv: -kv[1]):
                out.write(f"{key}\t{word}\t{weight}\n")
                total += 1
    print(f"wrote {total} entries to {TSV_OUT}", file=sys.stderr)

    with open(SYLLABLES_OUT, "w", encoding="utf-8") as f:
        f.write("// Generated by tools/build-dict.py from rime-ice pinyin columns. Do not hand-edit.\n")
        f.write("// The set of legal pinyin syllables usable by the segmenter — every syllable here\n")
        f.write("// is guaranteed to have at least one dictionary entry (see words.dict.tsv).\n")
        f.write("export const LEGAL_SYLLABLES: string[] = [\n")
        for s in sorted(syllables):
            f.write(f"  '{s}',\n")
        f.write("];\n")
    print(f"wrote {len(syllables)} syllables to {SYLLABLES_OUT}", file=sys.stderr)


if __name__ == "__main__":
    main()
